#!/usr/bin/env python3
"""Generate and verify requirements files for optional extras.

Usage:
    python .github/scripts/sync_requirements.py          # Generate all
    python .github/scripts/sync_requirements.py --check  # Verify up-to-date (CI)
"""

from __future__ import annotations

import argparse
import subprocess
import sys
import tempfile
from pathlib import Path

REPO_ROOT = Path(__file__).parent.parent.parent
REQ_DIR = REPO_ROOT / "agent_cli" / "_requirements"

EXTRAS = ["rag", "memory", "vad", "whisper", "whisper-mlx", "tts", "tts-kokoro", "server"]


def _strip_header(content: str) -> str:
    """Strip the autogenerated header comment (contains absolute path)."""
    lines = content.splitlines(keepends=True)
    # Skip lines starting with #
    while lines and lines[0].startswith("#"):
        lines.pop(0)
    return "".join(lines)


def _run_uv_export(extra: str, output_file: Path) -> subprocess.CompletedProcess[bytes]:
    cmd = [
        "uv",
        "export",
        "--extra",
        extra,
        "--no-dev",
        "--no-emit-project",
        "--no-hashes",
        "-o",
        str(output_file),
    ]
    return subprocess.run(cmd, check=False, capture_output=True)


def generate_requirements() -> None:
    """Generate requirements files from uv.lock."""
    REQ_DIR.mkdir(parents=True, exist_ok=True)

    for extra in EXTRAS:
        print(f"Generating: {extra}")
        output_file = REQ_DIR / f"{extra}.txt"
        result = _run_uv_export(extra, output_file)
        if result.returncode != 0:
            print(f"Failed to generate {extra}: {result.stderr.decode()}", file=sys.stderr)
            sys.exit(1)

    print(f"Generated {len(EXTRAS)} requirements files")


def check_requirements() -> None:
    """Verify requirements files are up-to-date."""
    with tempfile.TemporaryDirectory() as tmpdir_str:
        tmpdir = Path(tmpdir_str)
        all_match = True

        for extra in EXTRAS:
            tmp_file = tmpdir / f"{extra}.txt"
            current_file = REQ_DIR / f"{extra}.txt"

            result = _run_uv_export(extra, tmp_file)
            if result.returncode != 0:
                print(f"Failed to generate {extra}: {result.stderr.decode()}", file=sys.stderr)
                sys.exit(1)

            if not current_file.exists():
                print(f"Missing: {extra}.txt")
                all_match = False
            elif _strip_header(tmp_file.read_text()) != _strip_header(current_file.read_text()):
                print(f"Out of date: {extra}.txt")
                all_match = False

        if not all_match:
            print("\nRequirements files are out of date.")
            print("Run: python .github/scripts/sync_requirements.py")
            sys.exit(1)

        print("All requirements files are up-to-date")


def main() -> None:
    """Entry point for the script."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Check if files are up-to-date")
    args = parser.parse_args()

    if args.check:
        check_requirements()
    else:
        generate_requirements()


if __name__ == "__main__":
    main()
