"""Configuration management commands for agent-cli."""

from __future__ import annotations

import os
import platform
import shutil
import subprocess
from pathlib import Path

import typer

from agent_cli.config import CONFIG_PATHS, _config_path
from agent_cli.core.utils import console

# Default location for user config
DEFAULT_CONFIG_PATH = Path.home() / ".config" / "agent-cli" / "config.toml"

config_app = typer.Typer(
    name="config",
    help="Manage agent-cli configuration files.",
    rich_markup_mode="markdown",
    invoke_without_command=True,
)


@config_app.callback()
def config_callback(ctx: typer.Context) -> None:
    """Manage agent-cli configuration files."""
    if ctx.invoked_subcommand is None:
        console.print(ctx.get_help())


# --- Config command options (module-level to avoid B008) ---
CONFIG_PATH_OPTION: Path | None = typer.Option(
    None,
    "--path",
    "-p",
    help="Path to config file. Uses auto-detection if not specified.",
)
CONFIG_PATH_INIT_OPTION: Path | None = typer.Option(
    None,
    "--path",
    "-p",
    help="Custom path for config file. Default: ~/.config/agent-cli/config.toml",
)
FORCE_OPTION: bool = typer.Option(
    False,  # noqa: FBT003
    "--force",
    "-f",
    help="Overwrite existing config without confirmation.",
)
VALUES_OPTION: bool = typer.Option(
    False,  # noqa: FBT003
    "--values",
    "-v",
    help="Show config file contents with syntax highlighting.",
)


def _get_editor() -> str:
    """Get the user's preferred editor.

    Checks $EDITOR, then $VISUAL, then falls back to platform defaults.
    """
    for env_var in ("EDITOR", "VISUAL"):
        editor = os.environ.get(env_var)
        if editor:
            return editor

    if platform.system() == "Windows":
        return "notepad"

    # Try common editors on Unix-like systems
    for editor in ("vim", "vi", "nano"):
        if shutil.which(editor):
            return editor

    return "vi"


def _generate_template() -> str:
    """Generate a config template with all options commented out."""
    header = """\
# agent-cli configuration file
# Generated by: agent-cli config init
#
# Uncomment and modify options as needed.
# Keys use dashes to match command-line arguments.
# Any option here can be overridden by a command-line argument.
#
# For full documentation, see: https://github.com/basnijholt/agent-cli
"""

    # Find the example config file relative to this module
    example_path = Path(__file__).parent.parent / "example.agent-cli-config.toml"
    if not example_path.exists():
        # Fallback: generate minimal template
        return header + _generate_minimal_template()

    example_content = example_path.read_text()

    lines = [header.rstrip()]
    skip_header = True  # Skip the original file's header comments

    for line in example_content.splitlines():
        stripped = line.strip()

        # Skip the original header comments (lines before first section)
        if skip_header:
            if stripped.startswith("["):
                skip_header = False
            else:
                continue

        # Keep section headers [defaults], [chat], etc.
        if (
            (stripped.startswith("[") and stripped.endswith("]"))
            or stripped.startswith("#")
            or not stripped
        ):
            lines.append(line)
        # Comment out actual config values
        else:
            lines.append(f"# {line}")

    return "\n".join(lines) + "\n"


def _generate_minimal_template() -> str:
    """Generate a minimal config template as fallback."""
    return """\

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# Default Settings
# These settings apply to all commands unless overridden in a command-specific
# section below.
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
[defaults]

# --- Provider Selection ---
# llm-provider = "ollama"
# asr-provider = "wyoming"
# tts-provider = "wyoming"

# --- API Keys ---
# openai-api-key = "sk-..."

# --- Audio Device Settings ---
# input-device-name = "default"
# output-device-name = "default"

# --- LLM Settings ---
# llm-ollama-model = "gemma3:4b"
# llm-ollama-host = "http://localhost:11434"

# --- General Behavior ---
# log-level = "WARNING"
# clipboard = true

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# Command-Specific Overrides
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

# [autocorrect]
# llm-provider = "openai"

# [chat]
# tts = true

# [transcribe]
# llm = true
"""


@config_app.command("init")
def config_init(
    path: Path | None = CONFIG_PATH_INIT_OPTION,
    force: bool = FORCE_OPTION,
) -> None:
    """Create a new config file with all options commented out.

    The generated config file serves as a template showing all available
    options. Uncomment and modify the options you want to customize.
    """
    target_path = path if path else DEFAULT_CONFIG_PATH

    if (
        target_path.exists()
        and not force
        and not typer.confirm(
            f"Config file already exists at {target_path}. Overwrite?",
        )
    ):
        console.print("[yellow]Aborted.[/yellow]")
        raise typer.Exit(0)

    # Create parent directories
    target_path.parent.mkdir(parents=True, exist_ok=True)

    # Generate and write template
    template_content = _generate_template()
    target_path.write_text(template_content)

    console.print(f"[green]Config file created at:[/green] {target_path}")
    console.print("\n[dim]Edit the file to customize your settings:[/dim]")
    console.print("  [cyan]agent-cli config edit[/cyan]")


@config_app.command("edit")
def config_edit(
    path: Path | None = CONFIG_PATH_OPTION,
) -> None:
    """Open the config file in your default editor.

    The editor is determined by: $EDITOR > $VISUAL > platform default.
    """
    config_file = path or _config_path(None)

    if config_file is None or not config_file.exists():
        console.print("[yellow]No config file found.[/yellow]")
        console.print(
            "\nRun [bold cyan]agent-cli config init[/bold cyan] to create one.",
        )
        console.print("\nSearched locations:")
        for p in CONFIG_PATHS:
            console.print(f"  - {p}")
        raise typer.Exit(1)

    editor = _get_editor()
    console.print(f"[dim]Opening {config_file} with {editor}...[/dim]")

    try:
        subprocess.run([editor, str(config_file)], check=True)
    except FileNotFoundError:
        console.print(f"[red]Editor '{editor}' not found.[/red]")
        console.print("Set $EDITOR environment variable to your preferred editor.")
        raise typer.Exit(1) from None
    except subprocess.CalledProcessError as e:
        console.print(f"[red]Editor exited with error code {e.returncode}[/red]")
        raise typer.Exit(e.returncode) from None


@config_app.command("show")
def config_show(
    path: Path | None = CONFIG_PATH_OPTION,
    values: bool = VALUES_OPTION,
) -> None:
    """Display the current config file location and optionally its contents."""
    config_file = _config_path(str(path) if path else None)

    if config_file is None:
        console.print("[yellow]No config file found.[/yellow]")
        console.print("\nSearched locations:")
        for p in CONFIG_PATHS:
            status = "[green]exists[/green]" if p.exists() else "[dim]not found[/dim]"
            console.print(f"  - {p} ({status})")
        console.print(
            "\nRun [bold cyan]agent-cli config init[/bold cyan] to create one.",
        )
        raise typer.Exit(0)

    console.print(f"[bold green]Config file:[/bold green] {config_file}")

    if values:
        from rich.syntax import Syntax  # noqa: PLC0415

        console.print()
        content = config_file.read_text()
        syntax = Syntax(content, "toml", theme="monokai", line_numbers=True)
        console.print(syntax)
